/**
 * Initial spec definitions. Editable afterwards in the admin (Taxonomy → Specs).
 * `de` holds the German labels so the German locale is ready when it is switched on.
 */
import type { SpecGroup } from '../../src/lib/constants'

export type SeedSpec = {
  key: string
  urlKey: string
  label: string
  shortLabel?: string
  de: { label: string; shortLabel?: string; help?: string; options?: Record<string, string> }
  dataType: 'number' | 'select' | 'multiselect' | 'boolean' | 'feature' | 'text'
  unit?: string
  unitCode?: string
  decimals?: number
  group: SpecGroup
  order: number
  universal?: boolean
  filterable?: boolean
  showInCompare?: boolean
  better?: 'high' | 'low'
  min?: number
  max?: number
  help?: string
  options?: { value: string; label: string }[]
  quickFilter?: { min?: number; label: string; de: string }
}

export const SPECS: SeedSpec[] = [
  // ── Energy & range ────────────────────────────────────────────────────────
  {
    key: 'energy_source',
    urlKey: 'energy',
    label: 'Energy source',
    de: {
      label: 'Energiequelle',
      help: 'Gelistet werden nur lokal emissionsfreie Antriebe, keine Hybride.',
      options: {
        bev: 'Batterieelektrisch',
        fcev: 'Wasserstoff-Brennstoffzelle',
        tethered: 'Kabelgebunden (Netzstrom)',
        'bev-tethered': 'Batterie + Kabel',
      },
    },
    dataType: 'select',
    group: 'energy',
    order: 10,
    universal: true,
    help: 'Only locally zero-emission drivetrains are listed, no hybrids.',
    options: [
      { value: 'bev', label: 'Battery-electric' },
      { value: 'fcev', label: 'Hydrogen fuel cell' },
      { value: 'tethered', label: 'Cable-powered (grid)' },
      { value: 'bev-tethered', label: 'Battery + cable' },
    ],
  },
  {
    key: 'battery_kwh',
    urlKey: 'battery',
    label: 'Battery capacity (usable)',
    shortLabel: 'Battery',
    de: { label: 'Batteriekapazität (nutzbar)', shortLabel: 'Batterie', help: 'Nutzbare Kapazität, sofern veröffentlicht.' },
    dataType: 'number',
    unit: 'kWh',
    unitCode: 'KWH',
    decimals: 1,
    group: 'energy',
    order: 20,
    universal: true,
    better: 'high',
    min: 0.1,
    max: 2000,
    help: 'Usable capacity where the manufacturer publishes it.',
  },
  {
    key: 'range_km',
    urlKey: 'range',
    label: 'Range',
    de: {
      label: 'Reichweite',
      help: 'WLTP bei Transportern und Pickups, sonst Herstellerangabe. Die reale Reichweite hängt von Last, Temperatur und Strecke ab.',
    },
    dataType: 'number',
    unit: 'km',
    unitCode: 'KMT',
    group: 'energy',
    order: 30,
    better: 'high',
    min: 1,
    max: 1500,
    help: 'WLTP for vans and pickups; manufacturer figure for trucks and buses. Real range depends on load, temperature and route.',
    quickFilter: { min: 300, label: 'Range 300 km+', de: 'Reichweite ab 300 km' },
  },
  {
    key: 'runtime_h',
    urlKey: 'runtime',
    label: 'Runtime',
    de: { label: 'Einsatzdauer', help: 'Herstellerangabe für typischen Einsatz; schwere Arbeit verkürzt sie.' },
    dataType: 'number',
    unit: 'h',
    unitCode: 'HUR',
    decimals: 1,
    group: 'energy',
    order: 40,
    better: 'high',
    min: 0.5,
    max: 48,
    help: 'Manufacturer figure for typical duty; heavy work shortens it.',
    quickFilter: { min: 8, label: 'Full shift (8 h+)', de: 'Volle Schicht (ab 8 h)' },
  },
  {
    key: 'consumption_kwh_100km',
    urlKey: 'consumption',
    label: 'Energy consumption',
    shortLabel: 'Consumption',
    de: { label: 'Energieverbrauch', shortLabel: 'Verbrauch' },
    dataType: 'number',
    unit: 'kWh/100 km',
    decimals: 1,
    group: 'energy',
    order: 50,
    better: 'low',
    min: 1,
    max: 400,
    filterable: false,
    help: 'Combined WLTP or manufacturer figure.',
  },
  {
    key: 'h2_tank_kg',
    urlKey: 'hydrogen',
    label: 'Hydrogen tank capacity',
    shortLabel: 'Hydrogen',
    de: { label: 'Wasserstoff-Tankinhalt', shortLabel: 'Wasserstoff' },
    dataType: 'number',
    unit: 'kg',
    unitCode: 'KGM',
    decimals: 1,
    group: 'energy',
    order: 60,
    better: 'high',
    filterable: false,
  },
  {
    key: 'chemistry',
    urlKey: 'chemistry',
    label: 'Cell chemistry',
    de: { label: 'Zellchemie', options: { 'sodium-ion': 'Natrium-Ionen', 'lead-acid': 'Blei-Säure' } },
    dataType: 'select',
    group: 'energy',
    order: 70,
    universal: true,
    options: [
      { value: 'lfp', label: 'LFP' },
      { value: 'nmc', label: 'NMC' },
      { value: 'nca', label: 'NCA' },
      { value: 'lto', label: 'LTO' },
      { value: 'sodium-ion', label: 'Sodium-ion' },
      { value: 'lead-acid', label: 'Lead-acid' },
    ],
  },
  {
    key: 'voltage',
    urlKey: 'voltage',
    label: 'System voltage',
    de: {
      label: 'Systemspannung',
      options: { v48: 'Niedervolt (≤ 96 V)', v400: '400-V-Klasse', v800: '800-V-Klasse' },
    },
    dataType: 'select',
    group: 'energy',
    order: 80,
    universal: true,
    options: [
      { value: 'v48', label: 'Low voltage (≤ 96 V)' },
      { value: 'v400', label: '400 V class' },
      { value: 'v800', label: '800 V class' },
    ],
  },
  // ── Charging ──────────────────────────────────────────────────────────────
  {
    key: 'dc_kw',
    urlKey: 'dc',
    label: 'DC charging power (max)',
    shortLabel: 'DC charging',
    de: { label: 'DC-Ladeleistung (max.)', shortLabel: 'DC-Laden' },
    dataType: 'number',
    unit: 'kW',
    unitCode: 'KWT',
    group: 'charging',
    order: 10,
    universal: true,
    better: 'high',
    min: 1,
    max: 3750,
    quickFilter: { min: 100, label: 'DC 100 kW+', de: 'DC ab 100 kW' },
  },
  {
    key: 'ac_kw',
    urlKey: 'ac',
    label: 'AC charging power (onboard)',
    shortLabel: 'AC charging',
    de: { label: 'AC-Ladeleistung (Onboard)', shortLabel: 'AC-Laden' },
    dataType: 'number',
    unit: 'kW',
    unitCode: 'KWT',
    decimals: 1,
    group: 'charging',
    order: 20,
    universal: true,
    better: 'high',
    min: 0.1,
    max: 44,
    filterable: false,
  },
  {
    key: 'charging',
    urlKey: 'ports',
    label: 'Charging interfaces',
    de: {
      label: 'Ladeschnittstellen',
      options: {
        cee: 'CEE-/Industriesteckdose',
        schuko: '230-V-Steckdose',
        panto: 'Pantograf',
        swap: 'Batteriewechsel',
        inductive: 'Induktiv',
      },
    },
    dataType: 'multiselect',
    group: 'charging',
    order: 30,
    universal: true,
    options: [
      { value: 'ccs2', label: 'CCS2' },
      { value: 'mcs', label: 'MCS (megawatt)' },
      { value: 'type2', label: 'Type 2 AC' },
      { value: 'cee', label: 'CEE / industrial socket' },
      { value: 'schuko', label: '230 V socket' },
      { value: 'panto', label: 'Pantograph' },
      { value: 'swap', label: 'Battery swap' },
      { value: 'inductive', label: 'Inductive' },
    ],
  },
  {
    key: 'charge_time_dc_min',
    urlKey: 'charge-time',
    label: 'DC charging time (10–80 %)',
    shortLabel: 'DC 10–80 %',
    de: { label: 'DC-Ladezeit (10–80 %)', shortLabel: 'DC 10–80 %' },
    dataType: 'number',
    unit: 'min',
    unitCode: 'MIN',
    group: 'charging',
    order: 40,
    better: 'low',
    min: 5,
    max: 600,
    filterable: false,
    help: 'Manufacturer figure at a charger delivering the maximum power.',
  },
  {
    key: 'v2x',
    urlKey: 'v2x',
    label: 'Bidirectional charging (V2L / V2G)',
    shortLabel: 'V2L / V2G',
    de: { label: 'Bidirektionales Laden (V2L / V2G)', shortLabel: 'V2L / V2G' },
    dataType: 'feature',
    group: 'charging',
    order: 50,
    universal: true,
    quickFilter: { label: 'V2L / V2G', de: 'V2L / V2G' },
  },
  {
    key: 'heat_pump',
    urlKey: 'heat-pump',
    label: 'Heat pump',
    de: { label: 'Wärmepumpe' },
    dataType: 'feature',
    group: 'charging',
    order: 60,
  },
  // ── Drivetrain & performance ─────────────────────────────────────────────
  {
    key: 'power_kw',
    urlKey: 'power',
    label: 'Motor power (peak)',
    shortLabel: 'Power',
    de: { label: 'Motorleistung (Spitze)', shortLabel: 'Leistung' },
    dataType: 'number',
    unit: 'kW',
    unitCode: 'KWT',
    group: 'performance',
    order: 10,
    universal: true,
    better: 'high',
    min: 0.1,
    max: 2000,
  },
  {
    key: 'torque_nm',
    urlKey: 'torque',
    label: 'Torque (max)',
    shortLabel: 'Torque',
    de: { label: 'Drehmoment (max.)', shortLabel: 'Drehmoment' },
    dataType: 'number',
    unit: 'Nm',
    unitCode: 'NU',
    group: 'performance',
    order: 20,
    better: 'high',
    filterable: false,
  },
  {
    key: 'drive',
    urlKey: 'drive',
    label: 'Drive / axle configuration',
    shortLabel: 'Drive',
    de: { label: 'Antrieb / Achskonfiguration', shortLabel: 'Antrieb', options: { awd: 'Allrad (AWD / 4×4)', tracks: 'Raupenfahrwerk' } },
    dataType: 'select',
    group: 'performance',
    order: 30,
    universal: true,
    options: [
      { value: 'fwd', label: 'FWD' },
      { value: 'rwd', label: 'RWD' },
      { value: 'awd', label: 'AWD / 4×4' },
      { value: '4x2', label: '4×2' },
      { value: '6x2', label: '6×2' },
      { value: '6x4', label: '6×4' },
      { value: '8x4', label: '8×4' },
      { value: 'tracks', label: 'Tracks' },
    ],
  },
  {
    key: 'top_speed_kmh',
    urlKey: 'speed',
    label: 'Top speed',
    de: { label: 'Höchstgeschwindigkeit' },
    dataType: 'number',
    unit: 'km/h',
    unitCode: 'KMH',
    group: 'performance',
    order: 40,
    better: 'high',
    min: 1,
    max: 250,
  },
  {
    key: 'max_slope_deg',
    urlKey: 'slope',
    label: 'Max. working slope',
    shortLabel: 'Max. slope',
    de: { label: 'Max. Arbeitshangneigung', shortLabel: 'Max. Hangneigung' },
    dataType: 'number',
    unit: '°',
    unitCode: 'DD',
    group: 'performance',
    order: 50,
    better: 'high',
    min: 1,
    max: 90,
  },
  {
    key: 'noise_db',
    urlKey: 'noise',
    label: 'Sound power level',
    shortLabel: 'Noise',
    de: { label: 'Schallleistungspegel', shortLabel: 'Lärm', help: 'Garantierter Schallleistungspegel LwA, sofern veröffentlicht.' },
    dataType: 'number',
    unit: 'dB(A)',
    unitCode: '2N',
    group: 'performance',
    order: 60,
    better: 'low',
    min: 20,
    max: 140,
    help: 'Guaranteed sound power level LwA where published.',
  },
  // ── Dimensions & weights ──────────────────────────────────────────────────
  {
    key: 'gvw_t',
    urlKey: 'gvw',
    label: 'Gross vehicle weight (max)',
    shortLabel: 'GVW',
    de: { label: 'Zulässiges Gesamtgewicht (max.)', shortLabel: 'zGG' },
    dataType: 'number',
    unit: 't',
    unitCode: 'TNE',
    decimals: 2,
    group: 'dimensions',
    order: 10,
    min: 0.1,
    max: 60,
    help: 'Highest permissible gross weight of this version.',
  },
  {
    key: 'gcw_t',
    urlKey: 'gcw',
    label: 'Gross combination weight (max)',
    shortLabel: 'GCW',
    de: { label: 'Zulässiges Zuggesamtgewicht (max.)', shortLabel: 'zGG Zug' },
    dataType: 'number',
    unit: 't',
    unitCode: 'TNE',
    decimals: 1,
    group: 'dimensions',
    order: 20,
    better: 'high',
    min: 1,
    max: 250,
  },
  {
    key: 'op_weight_kg',
    urlKey: 'weight',
    label: 'Operating weight',
    de: { label: 'Einsatzgewicht' },
    dataType: 'number',
    unit: 'kg',
    unitCode: 'KGM',
    group: 'dimensions',
    order: 30,
    min: 1,
    max: 400000,
  },
  {
    key: 'length_m',
    urlKey: 'length',
    label: 'Length',
    de: { label: 'Länge' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'dimensions',
    order: 40,
    min: 0.3,
    max: 30,
  },
  {
    key: 'width_m',
    urlKey: 'width',
    label: 'Width',
    de: { label: 'Breite' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'dimensions',
    order: 50,
    min: 0.3,
    max: 5,
  },
  {
    key: 'height_m',
    urlKey: 'height',
    label: 'Height',
    de: { label: 'Höhe' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'dimensions',
    order: 60,
    min: 0.3,
    max: 6,
  },
  {
    key: 'turning_circle_m',
    urlKey: 'turning',
    label: 'Turning circle',
    de: { label: 'Wendekreis' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 1,
    group: 'dimensions',
    order: 70,
    better: 'low',
    filterable: false,
  },
  // ── Load & passenger capacity ─────────────────────────────────────────────
  {
    key: 'payload_kg',
    urlKey: 'payload',
    label: 'Payload (max)',
    shortLabel: 'Payload',
    de: { label: 'Nutzlast (max.)', shortLabel: 'Nutzlast' },
    dataType: 'number',
    unit: 'kg',
    unitCode: 'KGM',
    group: 'capacity',
    order: 10,
    better: 'high',
    min: 1,
    max: 60000,
    quickFilter: { min: 1000, label: 'Payload 1 t+', de: 'Nutzlast ab 1 t' },
  },
  {
    key: 'cargo_m3',
    urlKey: 'volume',
    label: 'Load volume (max)',
    shortLabel: 'Load volume',
    de: { label: 'Ladevolumen (max.)', shortLabel: 'Ladevolumen' },
    dataType: 'number',
    unit: 'm³',
    unitCode: 'MTQ',
    decimals: 1,
    group: 'capacity',
    order: 20,
    better: 'high',
    min: 0.01,
    max: 120,
  },
  {
    key: 'body_volume_m3',
    urlKey: 'body-volume',
    label: 'Body volume',
    de: { label: 'Aufbauvolumen' },
    dataType: 'number',
    unit: 'm³',
    unitCode: 'MTQ',
    decimals: 1,
    group: 'capacity',
    order: 25,
    better: 'high',
    help: 'Refuse body or tipper volume.',
  },
  {
    key: 'passengers',
    urlKey: 'passengers',
    label: 'Passenger capacity (total)',
    shortLabel: 'Passengers',
    de: { label: 'Fahrgastkapazität (gesamt)', shortLabel: 'Fahrgäste' },
    dataType: 'number',
    unit: 'pax',
    unitCode: 'C62',
    group: 'capacity',
    order: 30,
    better: 'high',
    min: 1,
    max: 300,
  },
  {
    key: 'seats',
    urlKey: 'seats',
    label: 'Seats (incl. driver)',
    shortLabel: 'Seats',
    de: { label: 'Sitzplätze (inkl. Fahrer)', shortLabel: 'Sitzplätze' },
    dataType: 'number',
    unitCode: 'C62',
    group: 'capacity',
    order: 40,
    min: 1,
    max: 120,
  },
  {
    key: 'towing_kg',
    urlKey: 'towing',
    label: 'Towing capacity',
    shortLabel: 'Towing',
    de: { label: 'Anhängelast', shortLabel: 'Anhängelast' },
    dataType: 'number',
    unit: 'kg',
    unitCode: 'KGM',
    group: 'capacity',
    order: 50,
    better: 'high',
    min: 1,
    max: 200000,
    help: 'Braked trailer load; drawbar capacity for tow tractors.',
  },
  // ── Work equipment ────────────────────────────────────────────────────────
  {
    key: 'lift_kg',
    urlKey: 'lift',
    label: 'Lift capacity',
    de: { label: 'Hubkraft / Tragfähigkeit', help: 'Nenntragfähigkeit; Kipplast bei Ladern; Hubkraft Heckhydraulik bei Traktoren.' },
    dataType: 'number',
    unit: 'kg',
    unitCode: 'KGM',
    group: 'work',
    order: 10,
    better: 'high',
    min: 1,
    max: 100000,
    help: 'Rated capacity; tipping load for loaders; rear hitch lift for tractors; platform capacity for work platforms.',
  },
  {
    key: 'lift_height_m',
    urlKey: 'lift-height',
    label: 'Lift height (max)',
    shortLabel: 'Lift height',
    de: { label: 'Hubhöhe (max.)', shortLabel: 'Hubhöhe' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'work',
    order: 20,
    better: 'high',
  },
  {
    key: 'working_height_m',
    urlKey: 'working-height',
    label: 'Working height (max)',
    shortLabel: 'Working height',
    de: { label: 'Arbeitshöhe (max.)', shortLabel: 'Arbeitshöhe' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 1,
    group: 'work',
    order: 30,
    better: 'high',
  },
  {
    key: 'outreach_m',
    urlKey: 'outreach',
    label: 'Outreach (max)',
    shortLabel: 'Outreach',
    de: { label: 'Reichweite Ausleger (max.)', shortLabel: 'Ausladung' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'work',
    order: 40,
    better: 'high',
  },
  {
    key: 'dig_depth_m',
    urlKey: 'dig-depth',
    label: 'Digging depth (max)',
    shortLabel: 'Dig depth',
    de: { label: 'Grabtiefe (max.)', shortLabel: 'Grabtiefe' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'work',
    order: 50,
    better: 'high',
  },
  {
    key: 'bucket_m3',
    urlKey: 'bucket',
    label: 'Bucket capacity',
    de: { label: 'Schaufelinhalt' },
    dataType: 'number',
    unit: 'm³',
    unitCode: 'MTQ',
    decimals: 2,
    group: 'work',
    order: 60,
    better: 'high',
  },
  {
    key: 'hopper_m3',
    urlKey: 'hopper',
    label: 'Hopper volume',
    de: { label: 'Behältervolumen' },
    dataType: 'number',
    unit: 'm³',
    unitCode: 'MTQ',
    decimals: 1,
    group: 'work',
    order: 70,
    better: 'high',
  },
  {
    key: 'work_width_m',
    urlKey: 'work-width',
    label: 'Working width',
    de: { label: 'Arbeitsbreite', help: 'Kehr-, Mäh- oder Verdichtungsbreite.' },
    dataType: 'number',
    unit: 'm',
    unitCode: 'MTR',
    decimals: 2,
    group: 'work',
    order: 80,
    better: 'high',
    help: 'Sweeping, mowing or compaction width.',
  },
  {
    key: 'water_tank_l',
    urlKey: 'water',
    label: 'Water tank',
    de: { label: 'Wassertank' },
    dataType: 'number',
    unit: 'l',
    unitCode: 'LTR',
    group: 'work',
    order: 90,
    better: 'high',
  },
  {
    key: 'aux_hydraulics_lpm',
    urlKey: 'hydraulics',
    label: 'Auxiliary hydraulic flow',
    shortLabel: 'Aux. hydraulics',
    de: { label: 'Zusatzhydraulik (Förderstrom)', shortLabel: 'Zusatzhydraulik' },
    dataType: 'number',
    unit: 'l/min',
    unitCode: 'L2',
    group: 'work',
    order: 100,
    better: 'high',
    filterable: false,
  },
  {
    key: 'pto',
    urlKey: 'pto',
    label: 'Power take-off (PTO)',
    shortLabel: 'PTO',
    de: { label: 'Zapfwelle', shortLabel: 'Zapfwelle' },
    dataType: 'feature',
    group: 'work',
    order: 110,
  },
  // ── Configuration & operation ─────────────────────────────────────────────
  {
    key: 'eu_class',
    urlKey: 'class',
    label: 'EU vehicle class',
    shortLabel: 'Vehicle class',
    de: {
      label: 'EU-Fahrzeugklasse',
      shortLabel: 'Fahrzeugklasse',
      help: 'Zulassungsklasse; selbstfahrende Arbeitsmaschinen haben keine EU-Typgenehmigung für den Straßenverkehr.',
      options: {
        L: 'L · Leichtfahrzeug (L1e–L7e)',
        N1: 'N1 · Güter ≤ 3,5 t',
        N2: 'N2 · Güter 3,5–12 t',
        N3: 'N3 · Güter > 12 t',
        M2: 'M2 · Bus ≤ 5 t',
        M3: 'M3 · Bus > 5 t',
        T: 'T · Zugmaschine (Land-/Forstwirtschaft)',
        SPM: 'Selbstfahrende Arbeitsmaschine',
      },
    },
    dataType: 'select',
    group: 'operation',
    order: 10,
    universal: true,
    help: 'Registration class; self-propelled work machines are not EU type-approved for public roads.',
    options: [
      { value: 'L', label: 'L · light vehicle (L1e–L7e)' },
      { value: 'N1', label: 'N1 · goods ≤ 3.5 t' },
      { value: 'N2', label: 'N2 · goods 3.5–12 t' },
      { value: 'N3', label: 'N3 · goods > 12 t' },
      { value: 'M2', label: 'M2 · bus ≤ 5 t' },
      { value: 'M3', label: 'M3 · bus > 5 t' },
      { value: 'T', label: 'T · agricultural tractor' },
      { value: 'SPM', label: 'Self-propelled work machine' },
    ],
  },
  {
    key: 'licence',
    urlKey: 'licence',
    label: 'Driving licence',
    de: {
      label: 'Führerscheinklasse',
      help: 'Typischerweise nötige EU-Klasse für die schwerste Version. Nationale Ausnahmen möglich, z. B. alternativ angetriebene Transporter bis 4,25 t mit Klasse B.',
      options: { T: 'T (Land-/Forstwirtschaft)', none: 'Nicht zulassungspflichtig' },
    },
    dataType: 'select',
    group: 'operation',
    order: 20,
    universal: true,
    help: 'EU licence category typically needed for the heaviest version. National exemptions may apply, e.g. alternatively fuelled vans up to 4.25 t on a B licence.',
    options: [
      { value: 'B', label: 'B' },
      { value: 'C1', label: 'C1' },
      { value: 'C', label: 'C' },
      { value: 'CE', label: 'CE' },
      { value: 'D1', label: 'D1' },
      { value: 'D', label: 'D' },
      { value: 'T', label: 'T (agricultural)' },
      { value: 'none', label: 'Not road-registered' },
    ],
  },
  {
    key: 'body',
    urlKey: 'body',
    label: 'Body & configuration',
    shortLabel: 'Body',
    de: {
      label: 'Aufbau & Konfiguration',
      shortLabel: 'Aufbau',
      options: {
        panel: 'Kastenwagen',
        crew: 'Doppelkabine / Mannschaft',
        chassis: 'Fahrgestell / Pritsche',
        box: 'Kofferaufbau',
        fridge: 'Kühlaufbau',
        tipper: 'Kipper',
        refuse: 'Müllpresse',
        mixer: 'Betonmischer',
        crane: 'Ladekran',
        flatbed: 'Pritsche / Plateau',
        curtain: 'Planenaufbau',
        pickupbed: 'Ladefläche (Pickup)',
        passenger: 'Personenbeförderung',
        fifth: 'Sattelkupplung',
        lowentry: 'Niederflurkabine',
        scissor: 'Scherenbühne',
        boom: 'Gelenk-/Teleskopbühne',
        mast: 'Mastbühne',
      },
    },
    dataType: 'multiselect',
    group: 'operation',
    order: 30,
    options: [
      { value: 'panel', label: 'Panel van' },
      { value: 'crew', label: 'Crew cab / crew van' },
      { value: 'chassis', label: 'Chassis cab / platform' },
      { value: 'box', label: 'Box body' },
      { value: 'fridge', label: 'Refrigerated' },
      { value: 'tipper', label: 'Tipper' },
      { value: 'refuse', label: 'Refuse compactor' },
      { value: 'mixer', label: 'Concrete mixer' },
      { value: 'crane', label: 'Loader crane' },
      { value: 'flatbed', label: 'Flatbed / dropside' },
      { value: 'curtain', label: 'Curtainsider' },
      { value: 'pickupbed', label: 'Pickup bed' },
      { value: 'passenger', label: 'Passenger' },
      { value: 'fifth', label: 'Fifth wheel' },
      { value: 'lowentry', label: 'Low-entry cab' },
      { value: 'scissor', label: 'Scissor lift' },
      { value: 'boom', label: 'Boom lift' },
      { value: 'mast', label: 'Vertical mast' },
    ],
  },
  {
    key: 'implements',
    urlKey: 'implements',
    label: 'Implements & attachments',
    shortLabel: 'Implements',
    de: {
      label: 'Anbaugeräte',
      shortLabel: 'Anbaugeräte',
      options: {
        bucket: 'Schaufel / Löffel',
        forks: 'Palettengabel',
        sweeper: 'Kehrmaschine',
        plough: 'Schneepflug',
        spreader: 'Winterstreuer',
        mower: 'Mähwerk',
        flail: 'Schlegelmäher',
        hitch: 'Dreipunkt-Anbau',
        blade: 'Planierschild',
        breaker: 'Hydraulikhammer',
        washer: 'Hochdruckreiniger',
      },
    },
    dataType: 'multiselect',
    group: 'operation',
    order: 40,
    options: [
      { value: 'bucket', label: 'Bucket' },
      { value: 'forks', label: 'Pallet forks' },
      { value: 'sweeper', label: 'Sweeping unit' },
      { value: 'plough', label: 'Snow plough' },
      { value: 'spreader', label: 'Winter spreader' },
      { value: 'mower', label: 'Mower deck' },
      { value: 'flail', label: 'Flail mower' },
      { value: 'hitch', label: 'Three-point hitch' },
      { value: 'blade', label: 'Dozer blade' },
      { value: 'breaker', label: 'Hydraulic breaker' },
      { value: 'washer', label: 'High-pressure washer' },
    ],
  },
  {
    key: 'operation',
    urlKey: 'operation',
    label: 'Operation mode',
    shortLabel: 'Operation',
    de: {
      label: 'Bedienung',
      options: { onboard: 'Mit Fahrer', remote: 'Ferngesteuert', autonomous: 'Autonomiefähig' },
    },
    dataType: 'multiselect',
    group: 'operation',
    order: 50,
    universal: true,
    options: [
      { value: 'onboard', label: 'Driver on board' },
      { value: 'remote', label: 'Remote-controlled' },
      { value: 'autonomous', label: 'Autonomous-ready' },
    ],
  },
  {
    key: 'quiet_cert',
    urlKey: 'quiet',
    label: 'Low-noise certified (e.g. PIEK)',
    shortLabel: 'Low-noise certified',
    de: { label: 'Geräuscharm zertifiziert (z. B. PIEK)', shortLabel: 'Geräuscharm zertifiziert' },
    dataType: 'boolean',
    group: 'operation',
    order: 60,
    help: 'Certified for quiet night-time delivery, e.g. PIEK (≤ 60 dB(A)).',
    quickFilter: { label: 'Low-noise certified', de: 'Geräuscharm zertifiziert' },
  },
  // ── Price & warranty ──────────────────────────────────────────────────────
  {
    key: 'price_eur',
    urlKey: 'price',
    label: 'List price from (net)',
    shortLabel: 'Price',
    de: { label: 'Listenpreis ab (netto)', shortLabel: 'Preis', help: 'Netto-Listenpreis in Deutschland, sofern veröffentlicht; ohne MwSt. und Förderung.' },
    dataType: 'number',
    unit: '€',
    unitCode: 'EUR',
    group: 'commercial',
    order: 10,
    universal: true,
    better: 'low',
    min: 100,
    max: 2000000,
    help: 'Net list price in Germany where published, excluding VAT and subsidies.',
  },
  {
    key: 'battery_warranty_years',
    urlKey: 'warranty',
    label: 'Battery warranty',
    de: { label: 'Batteriegarantie' },
    dataType: 'number',
    unit: 'years',
    unitCode: 'ANN',
    group: 'commercial',
    order: 20,
    universal: true,
    better: 'high',
    min: 1,
    max: 20,
    filterable: false,
  },
]
