/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    listings: Listing;
    brands: Brand;
    media: Media;
    documents: Document;
    'vehicle-types': VehicleType;
    jobs: Job;
    specs: Spec;
    'landing-pages': LandingPage;
    guides: Guide;
    pages: Page;
    'change-requests': ChangeRequest;
    placements: Placement;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    brands: {
      listings: 'listings';
    };
    'vehicle-types': {
      children: 'vehicle-types';
      listings: 'listings';
    };
    jobs: {
      children: 'jobs';
    };
  };
  collectionsSelect: {
    listings: ListingsSelect<false> | ListingsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'vehicle-types': VehicleTypesSelect<false> | VehicleTypesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    specs: SpecsSelect<false> | SpecsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'change-requests': ChangeRequestsSelect<false> | ChangeRequestsSelect<true>;
    placements: PlacementsSelect<false> | PlacementsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    settings: Setting;
    pricing: Pricing;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One listing per model version (e.g. each battery size). Versions of the same model share a "Model family".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title?: string | null;
  brand: number | Brand;
  /**
   * Model and version without brand, e.g. "PV5 Cargo Long Range".
   */
  model: string;
  /**
   * Same for all versions of a model, e.g. "PV5 Cargo". Links versions together.
   */
  family?: string | null;
  /**
   * Exactly one type. It decides which specs and key figures the listing shows.
   */
  vehicleType: number | VehicleType;
  availability: 'on-sale' | 'orders-open' | 'announced' | 'discontinued';
  /**
   * What it is used for. Tick all that apply; they link to job pages.
   */
  jobs?: (number | Job)[] | null;
  /**
   * One or two factual sentences for cards, search and the listing intro.
   */
  summary: string;
  specs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 3 lines, max 90 characters each.
   */
  keyFacts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pro partners only. 3 lines, max 90 characters each.
   */
  keyBenefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The first photo is the cover. Photos are cropped to 4:3 around their focal point, so every listing looks the same.
   */
  images?: (number | Media)[] | null;
  /**
   * Brochures, data sheets, price lists. Shown for Starter and Pro partners.
   */
  documents?:
    | {
        title: string;
        kind: 'brochure' | 'datasheet' | 'pricelist' | 'manual' | 'certificate' | 'video' | 'other';
        language?: ('en' | 'de' | 'fr' | 'nl' | 'it' | 'es' | 'pl' | 'multi') | null;
        file?: (number | null) | Document;
        /**
         * Or link to the manufacturer’s file.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Official product page. Shown as "Manufacturer page" (plain link).
   */
  sourceUrl?: string | null;
  /**
   * Further public sources used for the specs (press releases, data sheets).
   */
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shows "Data confirmed by <brand>" for 12 months while the brand has an active paid partnership. It means the manufacturer reviewed the data on this date; it is not a quality seal.
   */
  verifiedAt?: string | null;
  internalNotes?: string | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  /**
   * Same in all languages, e.g. "kia-pv5-cargo-long-range". Generated from brand + model. Changing it later creates a redirect.
   */
  slug?: string | null;
  /**
   * Contains fictional sample content (development only).
   */
  demo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One entry per brand as buyers know it (e.g. "Volvo" trucks and "Volvo CE" machines are separate brands). Partnership data drives badges, contacts, benefits and paid visibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * URL segment. Generated from the name if empty. Changing it later creates a redirect from the old URL.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  /**
   * Country of origin, e.g. "Germany".
   */
  country?: string | null;
  /**
   * Two or three factual sentences shown on the brand page.
   */
  description?: string | null;
  /**
   * One line for the brand spotlight (paid placement).
   */
  tagline?: string | null;
  contact?: {
    name?: string | null;
    role?: string | null;
    email?: string | null;
    phone?: string | null;
    /**
     * e.g. "Germany & Austria"
     */
    region?: string | null;
  };
  partnership: {
    tier: 'free' | 'starter' | 'pro';
    /**
     * Paid features switch off after this date.
     */
    validUntil?: string | null;
    /**
     * "manual" = invoiced outside Stripe.
     */
    subscriptionStatus?: ('none' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'manual') | null;
    /**
     * Rank this brand’s listings higher in the default "Recommended" order (Pro before Starter before free). Always labelled "Sponsored".
     */
    boostInRecommended?: boolean | null;
    /**
     * Subtle emphasis on result cards (Pro only). Always labelled.
     */
    highlightCards?: boolean | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    /**
     * Quantity on the Stripe subscription.
     */
    billedModels?: number | null;
  };
  /**
   * Fictional sample partner data for development. Never use in production.
   */
  demo?: boolean | null;
  listings?: {
    docs?: (number | Listing)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos are cropped to a standard 4:3 frame around the focal point and converted to WebP. Minimum width 1200 px. Store credit and licence for every image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo, e.g. "Kia PV5 Cargo, side view, white".
   */
  alt: string;
  /**
   * Shown under the photo, e.g. "Photo: Kia Europe".
   */
  credit: string;
  licence: 'press-kit' | 'manufacturer-permission' | 'own' | 'cc-by' | 'cc-by-sa' | 'other';
  /**
   * Where the photo comes from.
   */
  sourceUrl?: string | null;
  view?: ('side' | 'front34' | 'rear34' | 'interior' | 'cargo' | 'action' | 'detail') | null;
  licenceNote?: string | null;
  uploadedBy?: (number | null) | User;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins manage everything incl. users and billing. Editors edit and publish content. Partners edit their own brand as drafts that staff approve.
   */
  role: 'admin' | 'editor' | 'partner';
  /**
   * Partners can only see and edit listings of this brand.
   */
  brand?: (number | null) | Brand;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Two levels: groups (no parent) and types (with a parent group). Listings attach to types. A type inherits the spec profile and key figures of its group and can add its own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-types".
 */
export interface VehicleType {
  id: number;
  name: string;
  /**
   * URL segment. Generated from the name if empty. Changing it later creates a redirect from the old URL.
   */
  slug?: string | null;
  /**
   * Empty = this is a group (level 1). Set a group to make this a type (level 2).
   */
  parent?: (number | null) | VehicleType;
  /**
   * Cross-listing: also show this type under other groups (e.g. refuse trucks under Municipal and Trucks). The breadcrumb keeps the main group.
   */
  alsoListedIn?: (number | VehicleType)[] | null;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  /**
   * Drawing used when a listing has no photo. Types inherit it from their group.
   */
  illustration?:
    | (
        | 'van'
        | 'pickup'
        | 'utv'
        | 'micro'
        | 'bike'
        | 'truck'
        | 'tractor'
        | 'bus'
        | 'refuse'
        | 'sweeper'
        | 'carrier'
        | 'excavator'
        | 'loader'
        | 'telehandler'
        | 'dumper'
        | 'roller'
        | 'platform'
        | 'agtractor'
        | 'mower'
        | 'forklift'
        | 'yard'
        | 'tug'
      )
    | null;
  /**
   * One sentence, e.g. "Panel and crew vans up to 4.25 t".
   */
  shortDescription?: string | null;
  /**
   * Editorial intro for the hub page, 80–200 words: what defines this type, typical buyers, what to compare. Link to related hubs and guides.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the page and marked up as FAQPage. Aim for 3–5 real buyer questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Comma-separated search terms and trade names, e.g. "RCV, bin lorry, garbage truck". Improves site search; never shown.
   */
  synonyms?: string | null;
  specs?: (number | Spec)[] | null;
  /**
   * Shown as tiles at the top of every listing; the first three also appear on result cards. Leave empty on a type to inherit from its group.
   */
  keyFigures?: (number | Spec)[] | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  children?: {
    docs?: (number | VehicleType)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  listings?: {
    docs?: (number | Listing)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Specification fields. The group decides the section on the listing page; the vehicle type decides whether the spec appears at all (unless universal).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs".
 */
export interface Spec {
  id: number;
  label: string;
  /**
   * For cards, key figure tiles and sort options, e.g. "Range".
   */
  shortLabel?: string | null;
  /**
   * Stable ID stored with every listing. Do not change once in use.
   */
  key: string;
  /**
   * Filter parameter in URLs: ?range_min=300. Keep short and stable.
   */
  urlKey: string;
  dataType: 'number' | 'select' | 'multiselect' | 'boolean' | 'feature' | 'text';
  /**
   * Shown after the value: kWh, km, kW, kg, t, m, m³, h, km/h, dB(A), l, €
   */
  unit?: string | null;
  /**
   * UN/CEFACT code for structured data (KWH, KMT, KWT, KGM, TNE, MTR, MTQ, HUR…).
   */
  unitCode?: string | null;
  /**
   * Max decimals shown. Empty = automatic.
   */
  decimals?: number | null;
  /**
   * Marks the best value in compare and enables sorting.
   */
  better?: ('none' | 'high' | 'low') | null;
  /**
   * Plausibility check: lowest accepted value.
   */
  min?: number | null;
  /**
   * Highest accepted value.
   */
  max?: number | null;
  /**
   * Explains the value, e.g. "WLTP for vans; manufacturer figure for trucks".
   */
  help?: string | null;
  /**
   * Choices. The value is stored with listings and used in URLs; keep it stable.
   */
  options?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional one-tap filter chip above results, e.g. "Range 300 km+".
   */
  quickFilter?: {
    enabled?: boolean | null;
    min?: number | null;
    label?: string | null;
  };
  /**
   * Section on the listing page.
   */
  group: 'energy' | 'charging' | 'performance' | 'dimensions' | 'capacity' | 'work' | 'operation' | 'commercial';
  /**
   * Order within its section.
   */
  order?: number | null;
  /**
   * Applies to every vehicle type (e.g. battery, price).
   */
  universal?: boolean | null;
  /**
   * Offer as a filter on hubs and search.
   */
  filterable?: boolean | null;
  showInCompare?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Two levels: areas (no parent) and jobs (with a parent area). Listings attach to jobs, many per listing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  name: string;
  /**
   * URL segment. Generated from the name if empty. Changing it later creates a redirect from the old URL.
   */
  slug?: string | null;
  /**
   * Empty = this is an area (level 1).
   */
  parent?: (number | null) | Job;
  order?: number | null;
  /**
   * Areas only: drawing for the area tile.
   */
  illustration?:
    | (
        | 'van'
        | 'pickup'
        | 'utv'
        | 'micro'
        | 'bike'
        | 'truck'
        | 'tractor'
        | 'bus'
        | 'refuse'
        | 'sweeper'
        | 'carrier'
        | 'excavator'
        | 'loader'
        | 'telehandler'
        | 'dumper'
        | 'roller'
        | 'platform'
        | 'agtractor'
        | 'mower'
        | 'forklift'
        | 'yard'
        | 'tug'
      )
    | null;
  shortDescription?: string | null;
  /**
   * Editorial intro for the hub, 80–200 words.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the page and marked up as FAQPage. Aim for 3–5 real buyer questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vehicle types typically used for this job. Used for related links.
   */
  typicalTypes?: (number | VehicleType)[] | null;
  /**
   * Comma-separated search terms, e.g. "refuse collection, bin collection".
   */
  synonyms?: string | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  children?: {
    docs?: (number | Job)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Brochures, data sheets and price lists (PDF). Shown on listings of Starter and Pro partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  kind: 'brochure' | 'datasheet' | 'pricelist' | 'manual' | 'certificate' | 'video' | 'other';
  language?: ('en' | 'de' | 'fr' | 'nl' | 'it' | 'es' | 'pl' | 'sv' | 'da' | 'multi') | null;
  uploadedBy?: (number | null) | User;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Curated combinations of a vehicle type (group or type) and a job (area or job). URL: /types/<type>/for/<job>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  internalTitle?: string | null;
  vehicleType: number | VehicleType;
  job: number | Job;
  /**
   * H1. Default: "Electric <type> for <job>".
   */
  title?: string | null;
  /**
   * 80–200 words: what matters for this job, which specs to compare.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the page and marked up as FAQPage. Aim for 3–5 real buyer questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * URL segment. Generated from the name if empty. Changing it later creates a redirect from the old URL.
   */
  slug?: string | null;
  /**
   * Two sentences for the guide list and the meta description.
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown on the page and marked up as FAQPage. Aim for 3–5 real buyer questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedTypes?: (number | VehicleType)[] | null;
  relatedJobs?: (number | Job)[] | null;
  relatedListings?: (number | Listing)[] | null;
  author?: {
    /**
     * Empty = site owner from Settings.
     */
    name?: string | null;
    role?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * About, methodology, "How ranking works", for manufacturers, imprint, privacy and partner terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Which page this is. The URL is fixed per key.
   */
  key:
    | 'about'
    | 'methodology'
    | 'how-ranking-works'
    | 'for-manufacturers'
    | 'imprint'
    | 'privacy'
    | 'partner-terms'
    | 'data';
  title: string;
  /**
   * Lead paragraph under the title.
   */
  intro?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the page and marked up as FAQPage. Aim for 3–5 real buyer questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the generated title (≤ 60 characters) and description (≤ 155).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Force noindex, e.g. for pages that are not ready.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Corrections from visitors and partner drafts waiting for review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-requests".
 */
export interface ChangeRequest {
  id: number;
  title: string;
  kind: 'correction' | 'partner-edit' | 'claim';
  status: 'new' | 'in-review' | 'applied' | 'rejected' | 'spam';
  locale?: string | null;
  listing?: (number | null) | Listing;
  brand?: (number | null) | Brand;
  /**
   * Field-level suggestions.
   */
  changes?:
    | {
        field: string;
        current?: string | null;
        proposed?: string | null;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  sourceUrl?: string | null;
  submitter?: {
    name?: string | null;
    email?: string | null;
    company?: string | null;
    relation?: ('buyer' | 'manufacturer' | 'dealer' | 'press' | 'other') | null;
  };
  internalNote?: string | null;
  fingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Featured listings (1–2 highlighted cards at the top of hubs and the home page) and brand spotlights. Always labelled on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements".
 */
export interface Placement {
  id: number;
  /**
   * Internal, e.g. "Kia PV5 – vans hub Q4".
   */
  name: string;
  kind: 'featured-listing' | 'brand-spotlight';
  brand: number | Brand;
  listings?: (number | Listing)[] | null;
  onHome?: boolean | null;
  onBrandHub?: boolean | null;
  onGuides?: boolean | null;
  /**
   * Type or group hubs (a group includes its types).
   */
  vehicleTypes?: (number | VehicleType)[] | null;
  /**
   * Job or area hubs (an area includes its jobs).
   */
  jobs?: (number | Job)[] | null;
  startsAt: string;
  endsAt: string;
  /**
   * Higher wins.
   */
  priority?: number | null;
  active?: boolean | null;
  /**
   * Internal: order number, contact, price.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Created automatically when a published slug changes. Paths without locale, e.g. /vehicles/old.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'vehicle-types';
        value: number | VehicleType;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'specs';
        value: number | Spec;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'change-requests';
        value: number | ChangeRequest;
      } | null)
    | ({
        relationTo: 'placements';
        value: number | Placement;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  model?: T;
  family?: T;
  vehicleType?: T;
  availability?: T;
  jobs?: T;
  summary?: T;
  specs?: T;
  keyFacts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keyBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  images?: T;
  documents?:
    | T
    | {
        title?: T;
        kind?: T;
        language?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  sourceUrl?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  verifiedAt?: T;
  internalNotes?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  slug?: T;
  demo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  country?: T;
  description?: T;
  tagline?: T;
  contact?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        phone?: T;
        region?: T;
      };
  partnership?:
    | T
    | {
        tier?: T;
        validUntil?: T;
        subscriptionStatus?: T;
        boostInRecommended?: T;
        highlightCards?: T;
        stripeCustomerId?: T;
        stripeSubscriptionId?: T;
        billedModels?: T;
      };
  demo?: T;
  listings?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  licence?: T;
  sourceUrl?: T;
  view?: T;
  licenceNote?: T;
  uploadedBy?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  language?: T;
  uploadedBy?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-types_select".
 */
export interface VehicleTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  alsoListedIn?: T;
  order?: T;
  illustration?: T;
  shortDescription?: T;
  intro?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  synonyms?: T;
  specs?: T;
  keyFigures?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  children?: T;
  listings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  order?: T;
  illustration?: T;
  shortDescription?: T;
  intro?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  typicalTypes?: T;
  synonyms?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  children?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs_select".
 */
export interface SpecsSelect<T extends boolean = true> {
  label?: T;
  shortLabel?: T;
  key?: T;
  urlKey?: T;
  dataType?: T;
  unit?: T;
  unitCode?: T;
  decimals?: T;
  better?: T;
  min?: T;
  max?: T;
  help?: T;
  options?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  quickFilter?:
    | T
    | {
        enabled?: T;
        min?: T;
        label?: T;
      };
  group?: T;
  order?: T;
  universal?: T;
  filterable?: T;
  showInCompare?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  internalTitle?: T;
  vehicleType?: T;
  job?: T;
  title?: T;
  intro?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedTypes?: T;
  relatedJobs?: T;
  relatedListings?: T;
  author?:
    | T
    | {
        name?: T;
        role?: T;
      };
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  intro?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-requests_select".
 */
export interface ChangeRequestsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  status?: T;
  locale?: T;
  listing?: T;
  brand?: T;
  changes?:
    | T
    | {
        field?: T;
        current?: T;
        proposed?: T;
        id?: T;
      };
  message?: T;
  sourceUrl?: T;
  submitter?:
    | T
    | {
        name?: T;
        email?: T;
        company?: T;
        relation?: T;
      };
  internalNote?: T;
  fingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements_select".
 */
export interface PlacementsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  brand?: T;
  listings?: T;
  onHome?: T;
  onBrandHub?: T;
  onGuides?: T;
  vehicleTypes?: T;
  jobs?: T;
  startsAt?: T;
  endsAt?: T;
  priority?: T;
  active?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  brand?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  tagline?: string | null;
  /**
   * Disclaimer in the footer and on listings.
   */
  notice?: string | null;
  contactEmail?: string | null;
  /**
   * For manufacturer enquiries.
   */
  partnersEmail?: string | null;
  organization?: {
    legalName?: string | null;
    logo?: (number | null) | Media;
    /**
     * Profiles, e.g. LinkedIn.
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  owner?: {
    name?: string | null;
    role?: string | null;
    bio?: string | null;
    /**
     * e.g. LinkedIn profile
     */
    url?: string | null;
  };
  /**
   * Publish /data with JSON and CSV downloads (docs/03 §6, decide in Phase 3).
   */
  openDataEnabled?: boolean | null;
  openDataLicence?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  tiers?:
    | {
        tier: 'free' | 'starter' | 'pro';
        name: string;
        /**
         * EUR net per listed model per year. 0 = free.
         */
        pricePerModelYear?: number | null;
        highlight?: boolean | null;
        description?: string | null;
        features?:
          | {
              text: string;
              included?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print under the tiers, e.g. "Prices are net. Working assumption, to be confirmed."
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  tagline?: T;
  notice?: T;
  contactEmail?: T;
  partnersEmail?: T;
  organization?:
    | T
    | {
        legalName?: T;
        logo?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  owner?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        url?: T;
      };
  openDataEnabled?: T;
  openDataLicence?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  tiers?:
    | T
    | {
        tier?: T;
        name?: T;
        pricePerModelYear?: T;
        highlight?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              included?: T;
              id?: T;
            };
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}