import { useId } from 'react'

import type { Illustration as IllustrationType } from '@/lib/constants'
import { illustrationSvg } from '@/lib/illustrations'

export function Illustration({
  type,
  seed,
  label,
  className,
}: {
  type: IllustrationType | null
  seed?: string
  label?: string
  className?: string
}) {
  const uid = useId().replace(/[^a-zA-Z0-9]/g, '')
  return (
    <span
      className={className}
      // Static SVG generated by our own code (no user input besides escaped labels).
      dangerouslySetInnerHTML={{ __html: illustrationSvg(type, { seed, label, uid: `i${uid}` }) }}
    />
  )
}
