import type { ImageRef } from '@/lib/catalog/types'
import { cn } from '@/lib/cn'
import type { Illustration as IllustrationType } from '@/lib/constants'

import { Illustration } from './Illustration'

/**
 * Photo in the standard 4:3 frame (pre-cropped renditions, responsive srcset) or the type illustration.
 * The frame has a fixed aspect ratio so every card and gallery has the same height.
 */
export function VehicleImage({
  image,
  illustration,
  seed,
  alt,
  sizes = '(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw',
  priority = false,
  illustrationLabel,
  className,
}: {
  image?: ImageRef | null
  illustration: IllustrationType | null
  seed: string
  alt: string
  sizes?: string
  priority?: boolean
  illustrationLabel?: string
  className?: string
}) {
  if (image) {
    const src = image.sizes.card ?? image.sizes.large ?? { url: image.url, width: image.width, height: image.height }
    const srcSet = (['thumb', 'card', 'large'] as const)
      .map((k) => image.sizes[k])
      .filter(Boolean)
      .map((s) => `${s!.url} ${s!.width}w`)
      .join(', ')
    return (
      <div className={cn('relative aspect-[4/3] overflow-hidden bg-surface-2', className)}>
        {/* eslint-disable-next-line @next/next/no-img-element -- renditions are pre-generated by Payload */}
        <img
          src={src.url}
          srcSet={srcSet || undefined}
          sizes={sizes}
          width={src.width}
          height={src.height}
          alt={image.alt || alt}
          loading={priority ? 'eager' : 'lazy'}
          fetchPriority={priority ? 'high' : undefined}
          decoding="async"
          className="absolute inset-0 size-full object-cover"
        />
      </div>
    )
  }
  return (
    <div className={cn('relative aspect-[4/3] overflow-hidden', className)}>
      <Illustration type={illustration} seed={seed} label={alt} className="absolute inset-0 block [&>svg]:size-full" />
      {illustrationLabel && (
        <span className="absolute bottom-2.5 left-2.5 rounded-md bg-surface/85 px-2 py-0.5 text-[10.5px] font-semibold tracking-[0.06em] text-muted uppercase backdrop-blur">
          {illustrationLabel}
        </span>
      )}
    </div>
  )
}
